// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4ZpEO8jAcU_YeuLHLYxM1sVAhlLGqJM',
    appId: '1:98042968599:web:c52b9255ca08115296ba52',
    messagingSenderId: '98042968599',
    projectId: 'nutrition-app-c4540',
    authDomain: 'nutrition-app-c4540.firebaseapp.com',
    storageBucket: 'nutrition-app-c4540.firebasestorage.app',
    measurementId: 'G-991NML4GFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsle_7d7Lrm_RwIMQFjDGrP4KlpBGh7bs',
    appId: '1:98042968599:android:7ed0f08e2642c2ff96ba52',
    messagingSenderId: '98042968599',
    projectId: 'nutrition-app-c4540',
    storageBucket: 'nutrition-app-c4540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJBGkoaWSC2S19zR8BdC4N_HeEv97ha9U',
    appId: '1:98042968599:ios:c023b609dcec019996ba52',
    messagingSenderId: '98042968599',
    projectId: 'nutrition-app-c4540',
    storageBucket: 'nutrition-app-c4540.firebasestorage.app',
    iosBundleId: 'com.example.fe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJBGkoaWSC2S19zR8BdC4N_HeEv97ha9U',
    appId: '1:98042968599:ios:c023b609dcec019996ba52',
    messagingSenderId: '98042968599',
    projectId: 'nutrition-app-c4540',
    storageBucket: 'nutrition-app-c4540.firebasestorage.app',
    iosBundleId: 'com.example.fe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4ZpEO8jAcU_YeuLHLYxM1sVAhlLGqJM',
    appId: '1:98042968599:web:18307350afa3425c96ba52',
    messagingSenderId: '98042968599',
    projectId: 'nutrition-app-c4540',
    authDomain: 'nutrition-app-c4540.firebaseapp.com',
    storageBucket: 'nutrition-app-c4540.firebasestorage.app',
    measurementId: 'G-TZ4TF9MQ0Q',
  );
}
